openapi: 3.0.0
info:
  title: r2-d2-api
  version: 0.0.1
  description: "R2-D2 is an API service to enrich and provide A&P to upstream services, such as JarvisBooking. It's also responsible to receive bookings from upstream services, enrich and route them to downstream services, such as CMHub."
  contact:
    name: Bruno Ricardo Siqueira
    url: 'https://smartbox.atlassian.net/wiki/spaces/MF/overview'
    email: bruno.siqueira@smartbox.com
  license:
    name: Copyrigh (c) Smartbox 2019
servers:
  - url: 'http://localhost:3000'
    description: api-mock
paths:
  /broadcast_listeners/channel_room_availabilities:
    post:
      operationId: postChannelRoomAvailability
      summary: Create or Update Channel Room Availabilities
      tags:
        - broadcast_listerners
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/channelroomavailability.v1.yaml
              examples:
                response-broadcast-channel-room-availabilities-01:
                  value:
                    rate_band_golden_id: RATE_BAND_01
                    room_golden_id: ROOM_01
                    partner_golden_id: PARTNER_01
                    start_date: '2019-10-23'
                    end_date: '2019-10-24'
                    stock: '10'
        '201':
          description: Saved
          content:
            application/json:
              schema:
                $ref: ./models/success.v1.yaml
              examples:
                response-broadcast-channel-room-availabilitie-02:
                  value:
                    uuid: c2a4c3ce-b717-45ba-b044-1ce6dd03e264
                    code: '200'
                    endpoint: /broadcast_listeners/channel_room_availabilities
                    description: Channel Room Availability Update received
                    count: 1
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
              examples:
                response-broadcast-channel-room-availabilitie-03:
                  value:
                    uuid: 8c872a9e-7e1f-463a-ad71-4351dd014724
                    code: '400'
                    endpoint: /broadcast_listeners/channel_room_availabilities
                    description: 'Bad request, malformed payload'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
              examples:
                response-broadcast-channel-room-availabilitie-04:
                  value:
                    uuid: 205c1953-f20d-470f-90fb-82f635bd7906
                    code: '401'
                    endpoint: /broadcast_listeners/channel_room_availabilities
                    description: Unauthorized
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
              examples:
                response-broadcast-channel-room-availabilitie-05:
                  value:
                    uuid: 81c2bafc-2dd6-4cfa-b17c-1314d0722fbb
                    code: '403'
                    endpoint: /broadcast_listeners/channel_room_availabilities
                    description: Forbidden
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
              examples:
                request-broadcast-channel-room-availabilitie-06:
                  value:
                    uuid: 08b680de-b932-425d-b733-548d68b74eea
                    code: '404'
                    endpoint: /broadcast_listeners/channel_room_availabilities
                    description: Not Found
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
              examples:
                request-broadcast-channel-room-availabilitie-07:
                  value:
                    uuid: 78215776-c323-465a-93d9-2a1201d4bcf9
                    code: '500'
                    endpoint: /broadcast_listeners/channel_room_availabilities
                    description: Internal Server Error
        '501':
          description: Not Implemented
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
              examples:
                request-broadcast-channel-room-availabilitie-08:
                  value:
                    uuid: df6bc308-3fe8-4ce7-91f0-42bda0f62f00
                    code: '501'
                    endpoint: /broadcast_listeners/channel_room_availabilities
                    description: Not Implemented
      description: Create or Update Products
      security:
        - apiKey: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./models/channelroomavailability.v1.yaml
            examples:
              request-broadcast-channel-room-availabilities-01:
                value:
                  rate_band_golden_id: RATE_BAND_01
                  room_golden_id: ROOM_01
                  partner_golden_id: PARTNER_01
                  start_date: '2019-10-23'
                  end_date: '2019-10-24'
                  stock: '10'
        description: Channel Room Availability
  /broadcast_listeners/partners:
    post:
      operationId: postPartners
      summary: Create or Update Partners
      tags:
        - broadcast_listerners
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/partner.v1.yaml
              examples:
                response-broadcast-partner-01:
                  value:
                    golden_id: 123456789
                    status: partner
                    currency: EUR
        '201':
          description: Saved
          content:
            application/json:
              schema:
                $ref: ./models/success.v1.yaml
              examples:
                response-broadcast-partner-02:
                  value:
                    uuid: 722586e2-0887-4204-be95-f3a69077c21a
                    code: '200'
                    endpoint: /broadcast_listeners/partners
                    description: Partner Update received
                    count: 1
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
              examples:
                response-broadcast-partner-03:
                  value:
                    uuid: 2f2aa35e-60a6-4d4c-93c0-85d7d815005c
                    code: '400'
                    endpoint: /broadcast_listeners/partners
                    description: 'Bad request, malformed payload'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
              examples:
                response-broadcast-partner-04:
                  value:
                    uuid: 96a08c1f-6d20-4219-b02c-0e74e841b9ba
                    code: '401'
                    endpoint: /broadcast_listeners/partners
                    description: Unauthorized
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
              examples:
                response-broadcast-partner-05:
                  value:
                    uuid: 7c2bda9e-d8d9-42e1-8d07-d68ef52817f7
                    code: '403'
                    endpoint: /broadcast_listeners/partners
                    description: Forbidden
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
              examples:
                response-broadcast-partner-06:
                  value:
                    uuid: 795d5ce2-322c-4297-a30c-607a73524616
                    code: '404'
                    endpoint: /broadcast_listeners/partners
                    description: Not Found
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
              examples:
                response-broadcast-partner-07:
                  value:
                    uuid: 0a6e02f8-c304-402c-b637-a841ec5bfe48
                    code: '500'
                    endpoint: /broadcast_listeners/partners
                    description: Internal Server Error
        '501':
          description: Not Implemented
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
              examples:
                response-broadcast-partner-08:
                  value:
                    uuid: bbe45611-b941-4846-a028-181fbf655e44
                    code: '501'
                    endpoint: /broadcast_listeners/partners
                    description: Not Implemented
      description: Create or Update Partners
      security:
        - apiKey: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./models/partner.v1.yaml
            examples:
              request-broadcast-partner-01:
                value:
                  golden_id: 123456789
                  status: partner
                  currency: EUR
        description: Partner
  /broadcast_listeners/products:
    post:
      operationId: postProducts
      summary: Create or Update Products
      tags:
        - broadcast_listerners
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/product.v1.yaml
              examples:
                response-broadcast-product-01:
                  value:
                    golden_id: '123456789'
                    name: This is a product
                    description: This is a product description
                    universe: STAY
                    is_sellable: true
                    is_reservable: true
                    partner_golden_id: 123456789
        '201':
          description: Saved
          content:
            application/json:
              schema:
                $ref: ./models/success.v1.yaml
              examples:
                response-broadcast-product-02:
                  value:
                    uuid: 722586e2-0887-4204-be95-f3a69077c21a
                    code: '200'
                    endpoint: /broadcast_listeners/products
                    description: Product Update received
                    count: 1
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
              examples:
                response-broadcast-product-03:
                  value:
                    uuid: 2f2aa35e-60a6-4d4c-93c0-85d7d815005c
                    code: '400'
                    endpoint: /broadcast_listeners/products
                    description: 'Bad request, malformed payload'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
              examples:
                response-broadcast-product-04:
                  value:
                    uuid: 96a08c1f-6d20-4219-b02c-0e74e841b9ba
                    code: '401'
                    endpoint: /broadcast_listeners/products
                    description: Unauthorized
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
              examples:
                response-broadcast-product-05:
                  value:
                    uuid: 7c2bda9e-d8d9-42e1-8d07-d68ef52817f7
                    code: '403'
                    endpoint: /broadcast_listeners/products
                    description: Forbidden
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
              examples:
                response-broadcast-product-06:
                  value:
                    uuid: 795d5ce2-322c-4297-a30c-607a73524616
                    code: '404'
                    endpoint: /broadcast_listeners/products
                    description: Not Found
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
              examples:
                response-broadcast-product-07:
                  value:
                    uuid: 0a6e02f8-c304-402c-b637-a841ec5bfe48
                    code: '500'
                    endpoint: /broadcast_listeners/products
                    description: Internal Server Error
        '501':
          description: Not Implemented
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
              examples:
                response-broadcast-product-08:
                  value:
                    uuid: bbe45611-b941-4846-a028-181fbf655e44
                    code: '501'
                    endpoint: /broadcast_listeners/products
                    description: Not Implemented
      description: Create or Update Products
      security:
        - apiKey: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./models/product.v1.yaml
            examples:
              request-broadcast-product-01:
                value:
                  golden_id: '123456789'
                  name: This is a product
                  description: This is a product description
                  universe: STAY
                  is_sellable: true
                  is_reservable: true
                  partner_golden_id: 123456789
        description: Product
  /broadcast_listeners/product_relationships:
    post:
      operationId: postProductRelationships
      summary: Create or Update Product Relationships
      tags:
        - broadcast_listerners
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/productrelationship.v1.yaml
              examples:
                response-broadcast-product-relationship-01:
                  value:
                    parent_product:
                      golden_id: PRODUCT 01
                    child_product:
                      golden_id: PRODUCT 02
                    is_enabled: true
        '201':
          description: Saved
          content:
            application/json:
              schema:
                $ref: ./models/productrelationship.v1.yaml
              examples:
                response-broadcast-product-relationship-02:
                  value:
                    code: '201'
                    endpoint: /broadcast_listeners/product_relationships
                    description: Product Relationship Update received
                    count: 1
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
              examples:
                response-broadcast-product-relationship-03:
                  value:
                    uuid: cf3b64d9-45fb-4202-9ff3-570051bf2677
                    code: '400'
                    endpoint: /broadcast_listeners/product_relationships
                    description: 'Bad request, malformed payload'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
              examples:
                response-broadcast-product-relationship-04:
                  value:
                    uuid: 316c78be-0881-46f5-b839-58bb2e6a0bb8
                    code: '401'
                    endpoint: /broadcast_listeners/product_relationships
                    description: Unauthorized
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
              examples:
                response-broadcast-product-relationship-05:
                  value:
                    uuid: be31a063-5d37-46b3-a704-394aacd18705
                    code: '403'
                    endpoint: /broadcast_listeners/product_relationships
                    description: Forbidden
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
              examples:
                example-1response-broadcast-product-relationship-06:
                  value:
                    uuid: f9f7595e-00fb-46e7-8d4c-efe3845a5e12
                    code: '404'
                    endpoint: /broadcast_listeners/product_relationships
                    description: Not Found
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
              examples:
                response-broadcast-product-relationship-07:
                  value:
                    uuid: bbc44708-fdbd-476c-aa74-af7a1edd9d65
                    code: '500'
                    endpoint: /broadcast_listeners/product_relationships
                    description: Internal Server Error
        '501':
          description: Not Implemented
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
              examples:
                response-broadcast-product-relationship-08:
                  value:
                    uuid: 98f04c72-19bd-480a-81d4-8da5e0e98a9e
                    code: '501'
                    endpoint: /broadcast_listeners/product_relationships
                    description: Not Implemented
      description: Create or Update Product Relationships
      security:
        - apiKey: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./models/productrelationship.v1.yaml
            examples:
              request-broadcast-product-relationship-01:
                value:
                  parent_product:
                    golden_id: PRODUCT 01
                  child_product:
                    golden_id: PRODUCT 02
                  is_enabled: true
        description: Product Relationship
      parameters:
        - schema:
            type: string
            enum:
              - simple
              - full
            default: full
          in: query
          name: response_type
  /room_prices:
    get:
      operationId: getRoomPrices
      summary: Get Room Prices collection
      tags:
        - room_prices
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./models/roomprice.v1.yaml
              examples:
                response-room-prices-01:
                  value: {}
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: ./models/success.v1.yaml
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
        '501':
          description: Not Implemented
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
      description: Get Room Prices collection
      security:
        - apiKey: []
      parameters:
        - schema:
            type: string
            enum:
              - cached
              - fresh
            default: cached
          in: query
          name: response_type
        - schema:
            type: number
            default: '0'
          in: query
          name: page_number
        - schema:
            type: number
            maximum: 1000
          in: query
          name: page_size
        - schema:
            type: string
          in: query
          name: experience_id
        - schema:
            type: string
          in: query
          name: partner_golden_id
        - schema:
            type: string
          in: query
          name: rate_band_golden_id
        - schema:
            type: string
          in: query
          name: room_golden_id
        - schema:
            type: string
          in: query
          name: box_golden_id
        - schema:
            type: string
          in: query
          name: start_date
        - schema:
            type: string
          in: query
          name: end_date
    put:
      operationId: putRoomPrices
      summary: Room Prices bulk update
      tags:
        - room_prices
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./models/roomprice.v1.yaml
        '201':
          description: Updated
          content:
            application/json:
              schema:
                $ref: ./models/success.v1.yaml
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
            application/xml:
              schema:
                type: object
                properties: {}
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
            application/xml:
              schema:
                type: object
                properties: {}
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
        '501':
          description: Not Implemented
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: ./models/roomprice.v1.yaml
        description: Collection of Room Prices
      parameters:
        - schema:
            type: string
            enum:
              - simple
              - full
            default: full
          in: query
          name: response_type
      security:
        - apiKey: []
      description: Room Prices bulk update
    patch:
      operationId: patchRoomPrices
      summary: Room Prices bulk partial update
      tags:
        - room_prices
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./models/roomprice.v1.yaml
        '201':
          description: Updated
          content:
            application/json:
              schema:
                $ref: ./models/success.v1.yaml
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
            application/xml:
              schema:
                type: object
                properties: {}
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
            application/xml:
              schema:
                type: object
                properties: {}
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
        '501':
          description: Not Implemented
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
      description: Room Prices bulk partial update
      security:
        - apiKey: []
      parameters:
        - schema:
            type: string
            enum:
              - simple
              - full
            default: full
          in: query
          name: response_type
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: ./models/patch.v1.yaml
        description: Collection of Patches
    post:
      operationId: postRoomPrices
      summary: Room Prices bulk creation
      tags:
        - room_prices
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./models/roomprice.v1.yaml
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: ./models/success.v1.yaml
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
        '501':
          description: Not Implemented
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
      description: Room Prices bulk creation
      parameters:
        - schema:
            type: string
            enum:
              - simple
              - full
            default: full
          in: query
          name: response_type
          description: ''
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: ./models/roomprice.v1.yaml
        description: Collection of Room Prices
      security:
        - apiKey: []
  /room_availabilities:
    get:
      operationId: getRoomAvailabilities
      summary: Get Room Availabilities collection
      tags:
        - room_availabilities
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./models/roomavailability.v1.yaml
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: ./models/success.v1.yaml
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
        '501':
          description: Not Implemented
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
      description: Get Room Availabilities collection
      security:
        - apiKey: []
      parameters:
        - schema:
            type: string
            enum:
              - cached
              - fresh
            default: cached
          in: query
          name: response_type
        - schema:
            type: number
            default: '0'
          in: query
          name: page_number
        - schema:
            type: number
            maximum: 1000
          in: query
          name: page_size
        - schema:
            type: string
          in: query
          name: experience_id
        - schema:
            type: string
          in: query
          name: partner_golden_id
        - schema:
            type: string
          in: query
          name: rate_band_golden_id
        - schema:
            type: string
          in: query
          name: room_golden_id
        - schema:
            type: string
          in: query
          name: box_golden_id
        - schema:
            type: string
          in: query
          name: start_date
        - schema:
            type: string
          in: query
          name: end_date
    put:
      operationId: putRoomAvailabilities
      summary: Room Availabilities bulk update
      tags:
        - room_availabilities
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./models/roomavailability.v1.yaml
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: ./models/success.v1.yaml
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
            application/xml:
              schema:
                type: object
                properties: {}
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
            application/xml:
              schema:
                type: object
                properties: {}
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
        '501':
          description: Not Implemented
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: ./models/roomavailability.v1.yaml
        description: Collection of Room Availabilities
      parameters:
        - schema:
            type: string
            enum:
              - simple
              - full
            default: full
          in: query
          name: response_type
      security:
        - apiKey: []
      description: Room Availabilities bulk update
    patch:
      operationId: patchRoomAvailabilities
      summary: Room Availabilities bulk partial update
      tags:
        - room_availabilities
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./models/roomavailability.v1.yaml
        '201':
          description: Updated
          content:
            application/json:
              schema:
                $ref: ./models/success.v1.yaml
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
            application/xml:
              schema:
                type: object
                properties: {}
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
            application/xml:
              schema:
                type: object
                properties: {}
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
        '501':
          description: Not Implemented
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
      description: Room Availabilities bulk partial update
      security:
        - apiKey: []
      parameters:
        - schema:
            type: string
            enum:
              - simple
              - full
            default: full
          in: query
          name: response_type
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: ./models/patch.v1.yaml
        description: Collection of Patches
    post:
      operationId: postRoomAvailabilities
      summary: Room Availabilities bulk creation
      tags:
        - room_availabilities
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./models/roomavailability.v1.yaml
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: ./models/success.v1.yaml
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
        '501':
          description: Not Implemented
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
      description: Room Availabilities bulk creation
      parameters:
        - schema:
            type: string
            enum:
              - simple
              - full
            default: full
          in: query
          name: response_type
          description: ''
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: ./models/roomavailability.v1.yaml
        description: Collection of Room Availabilities
      security:
        - apiKey: []
  /bookings:
    get:
      summary: Get Bookings collection
      tags:
        - bookings
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./models/booking.v1.yaml
              examples:
                response-bookings-01:
                  value:
                    - value:
                        golden_id: '123456789'
                        partner_golden_id: '00123'
                        experience_golden_id: '123'
                        voucher: '123456789123'
                        request_type: confirm
                        start_date: '2019-10-10'
                        end_date: '2019-10-11'
                        dates:
                          - room_golden_id: '00123'
                            rate_band_golden_id: RATEBAND01
                            date: '2019-10-10'
                            price: 22200
                            is_upsell: true
                            guests_count: 2
                        customer_golden_id: '111222333'
                        placed_at: '2019-10-01'
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: ./models/success.v1.yaml
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
        '501':
          description: Not Implemented
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
      description: Get Bookings collection
      operationId: getBookings
      security:
        - apiKey: []
      parameters:
        - schema:
            type: string
            enum:
              - cached
              - fresh
            default: cached
          in: query
          name: response_type
        - schema:
            type: number
            default: '0'
          in: query
          name: page_number
        - schema:
            type: number
            maximum: 1000
          in: query
          name: page_size
        - schema:
            type: string
          in: query
          name: experience_id
        - schema:
            type: string
          in: query
          name: partner_golden_id
        - schema:
            type: string
          in: query
          name: room_golden_id
        - schema:
            type: string
          in: query
          name: customer_golden_id
        - schema:
            type: string
          in: query
          name: start_date
        - schema:
            type: string
          in: query
          name: end_date
    post:
      summary: Bookings bulk creation
      tags:
        - bookings
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/booking.v1.yaml
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: ./models/success.v1.yaml
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
        '501':
          description: Not Implemented
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
      description: Bookings bulk creation
      operationId: postBookings
      security:
        - apiKey: []
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: ./models/booking.v1.yaml
        description: Collection of Bookings
      parameters:
        - schema:
            type: string
            enum:
              - simple
              - full
            default: full
          in: query
          name: response_type
    put:
      summary: Bookings bulk update
      tags:
        - bookings
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/booking.v1.yaml
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: ./models/success.v1.yaml
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
        '501':
          description: Not Implemented
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
      description: Bookings bulk update
      operationId: putBookings
      security:
        - apiKey: []
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: ./models/booking.v1.yaml
        description: Collection of Bookings
      parameters:
        - schema:
            type: string
            enum:
              - simple
              - full
            default: full
          in: query
          name: response_type
    patch:
      summary: Bookings bulk partial update
      tags:
        - bookings
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/patch.v1.yaml
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: ./models/success.v1.yaml
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
        '501':
          description: Not Implemented
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
      description: Bookings bulk partial update
      operationId: patchBookings
      security:
        - apiKey: []
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: ./models/patch.v1.yaml
        description: Collection of Patches
      parameters:
        - schema:
            type: string
            enum:
              - simple
              - full
            default: full
          in: query
          name: response_type
components:
  schemas: {}
  securitySchemes:
    apiKey:
      name: apiKey
      type: apiKey
      in: header
      description: API Key
